spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    enabled: true

custom:
  aws:
    iot:
      endPoint: "${IOT_ENDPOINT:a16vfhk388057-ats.iot.ap-northeast-2.amazonaws.com}"
      certificatePath: "${IOT_CERT_PATH:${user.dir}/auth/e997ace6397b2fc98c4f6a794e0ca0ee0f2504d608e5e0d4283a2b278eb5640d/certificate.pem.crt}"
      privateKeyPath: "${IOT_PRIVATE_KEY_PATH:${user.dir}/auth/e997ace6397b2fc98c4f6a794e0ca0ee0f2504d608e5e0d4283a2b278eb5640d/private.pem.key}"
  thing:
    name: "${THING_NAME:greenhouse-management-system-local}"
